resources:
- name: ci
  type: git
  icon: github
  source:
    uri: git@github.com:seabird-chat/seabird-ci.git
    private_key: ((github-ssh-key))

# Common variables shared between pipelines
common-vars: &common-vars
  github-ssh-key: ((github-ssh-key))
  ansible-ssh-key: ((ansible-ssh-key))
  registry-username: ((registry-username))
  registry-password: ((registry-password))
  ansible-vault-password: ((ansible-vault-password))

jobs:
# update this pipeline before updating child pipelines
- name: set-self
  plan:
  - get: ci
    trigger: true
  - set_pipeline: self
    file: ci/main.yml

- name: update-publish-pipelines
  plan:
  - get: ci
    trigger: true
    passed: [set-self]
  - in_parallel:
    # Core
    - set_pipeline: seabird-core-publish
      file: ci/build-and-publish.yml
      vars:
        <<: *common-vars
        repo-name: seabird-core

    # Backends
    - set_pipeline: seabird-discord-backend-publish
      file: ci/build-and-publish.yml
      vars:
        <<: *common-vars
        repo-name: seabird-discord-backend

    - set_pipeline: seabird-irc-backend-publish
      file: ci/build-and-publish.yml
      vars:
        <<: *common-vars
        repo-name: seabird-irc-backend

    # Plugin Bundle
    - set_pipeline: seabird-plugin-bundle-publish
      file: ci/build-and-publish.yml
      vars:
        <<: *common-vars
        repo-name: seabird-plugin-bundle

    # Plugins
    - set_pipeline: seabird-adventofcode-plugin-publish
      file: ci/build-and-publish.yml
      vars:
        <<: *common-vars
        repo-name: seabird-adventofcode-plugin

    - set_pipeline: seabird-github-plugin-publish
      file: ci/build-and-publish.yml
      vars:
        <<: *common-vars
        repo-name: seabird-github-plugin

    - set_pipeline: seabird-stock-plugin-publish
      file: ci/build-and-publish.yml
      vars:
        <<: *common-vars
        repo-name: seabird-stock-plugin

    - set_pipeline: seabird-url-plugin-publish
      file: ci/build-and-publish.yml
      vars:
        <<: *common-vars
        repo-name: seabird-url-plugin

    - set_pipeline: seabird-webhook-receiver-publish
      file: ci/build-and-publish.yml
      vars:
        <<: *common-vars
        repo-name: seabird-webhook-receiver
